### ISSUE TITLE
CLDR 27 and 28 not compatible

### ISSUE THREAD

**Issue by betaorbust** [yahoo/formatjs-extract-cldr-data#8]
Running `grunt update-cldr-data` fails because, since 27, CLDR data is no longer hosted in a json-full.zip file.

CLDR data is available in JSON format from https://github.com/unicode-cldr/cldr-json

**Comment by caridy** [comment]
@betaorbust it will take a little bit a work to do this switch. I have already done it in Intl.js, hopefully this one will be easier. @ericf do you plan to take this one?

**Comment by betaorbust** [comment]
Awesome. Thanks :+1:

**Comment by ericf** [comment]
Yeah this package needs to be refactored with how it sources the CLDR data. As you guys know, it can now be an npm dep.

I can look into refactoring it…

**Comment by ericf** [comment]
@betaorbust a PR is also welcome if you have the time to work on this… let me know.

**Comment by ericf** [comment]
@betaorbust @caridy I opened #10 if you guys want to take a look.
